name:
  - fish
channels:
  - defaults
dependencies:
  - numpy
  - scipy
  - scikit-learn
  - scikit-image
  - jupyter
  - pylint
  - flake8
  - pytest
  - autopep8
  - pip
  - pip:
      - opencv-python
      - imageio
      - matplotlib
